Allow linking mingw builds to the bundled SDL2 libraries
Order is significant when using traditional Unix linkers like GNU ld:
libraries later in the link line can provide symbols required by
libraries earlier in the link line, but the opposite is not true.
When using an external SDL2, FindSDL2.cmake puts SDL2main before SDL2,
because SDL2main uses symbols from SDL2. Do the same for the bundled
SDL2 library.

This fixes the following link errors:

.../lib/SDL2/lib/x86/SDL2main.lib(./Release/SDL_windows_main.obj):(.text[_main]+0x5): undefined reference to `SDL_SetMainReady'
.../lib/SDL2/lib/x86/SDL2main.lib(./Release/SDL_windows_main.obj):(.text[_WinMain@16]+0x14): undefined reference to `SDL_wcslen'
.../lib/SDL2/lib/x86/SDL2main.lib(./Release/SDL_windows_main.obj):(.text[_WinMain@16]+0x2f): undefined reference to `SDL_iconv_string'
.../lib/SDL2/lib/x86/SDL2main.lib(./Release/SDL_windows_main.obj):(.text[_WinMain@16]+0x63): undefined reference to `SDL_malloc'
.../lib/SDL2/lib/x86/SDL2main.lib(./Release/SDL_windows_main.obj):(.text[_ParseCommandLine]+0x36): undefined reference to `SDL_isspace'
.../lib/SDL2/lib/x86/SDL2main.lib(./Release/SDL_windows_main.obj):(.text[_ParseCommandLine]+0xf5): undefined reference to `SDL_isspace'
collect2: error: ld returned 1 exit status